---
fabric_name: AVD_FABRIC

service_routing_protocols_model: multi-agent

custom_structured_configuration_spanning_tree:
  mode: mstp

ip_routing: true

# Needed for Arista ATD Lab Environment
dns_domain: atd.lab
mgmt_interface: MGMT
mgmt_interface_vrf: MGMT
mgmt_gateway: 192.168.0.1
mgmt_vrf_routing: true

node_type_keys:

  - key: spine
    type: spine
    default_evpn_role: server
    default_ptp_priority1: 20

  - key: l3leaf
    type: l3leaf
    connected_endpoints: true
    default_evpn_role: client
    mlag_support: true
    network_services:
      l2: true
      l3: true
    vtep: true
    default_ptp_priority1: 30

  - key: gwleaf
    type: gwleaf
    connected_endpoints: true
    default_evpn_role: client
    mlag_support: true
    network_services:
      l2: true
      l3: true
    vtep: true
    default_ptp_priority1: 30
    ip_addressing:
      p2p_uplinks_ip: 
      p2p_uplinks_peer_ip: 

  - key: l2leaf
    type: l2leaf
    connected_endpoints: true
    mlag_support: true
    network_services:
      l2: true
    underlay_router: false
    uplink_type: port-channel

  - key: l3spine
    type: l3spine
    connected_endpoints: true
    mlag_support: true
    network_services:
      l2: true
      l3: true
    default_overlay_routing_protocol: none
    default_underlay_routing_protocol: none

  - key: l2spine
    type: spine
    connected_endpoints: true
    mlag_support: true
    network_services:
      l2: true
    underlay_router: false
    uplink_type: port-channel

  - key: super_spine
    type: super-spine

  - key: overlay_controller
    type: overlay-controller
    default_evpn_role: server

  - key: wan_router
    type: wan_router
    default_evpn_role: client
    default_underlay_routing_protocol: none
    default_overlay_routing_protocol: ibgp
    vtep: true
    network_services:
      l3: true

  - key: wan_rr
    type: wan_rr
    default_evpn_role: server
    default_underlay_routing_protocol: none
    default_overlay_routing_protocol: ibgp
    vtep: true
    network_services:
      l3: true

  - key: p
    type: p
    mpls_lsr: true
    default_mpls_overlay_role: none
    default_overlay_routing_protocol: ibgp
    default_underlay_routing_protocol: isis-sr

  - key: pe
    type: pe
    mpls_lsr: true
    connected_endpoints: true
    default_mpls_overlay_role: client
    default_evpn_role: client
    network_services:
      l1: true
      l2: true
      l3: true
    default_overlay_routing_protocol: ibgp
    default_underlay_routing_protocol: isis-sr
    default_overlay_address_families:
    - vpn-ipv4
    default_evpn_encapsulation: mpls

  - key: rr
    type: rr
    mpls_lsr: true
    default_mpls_overlay_role: server
    default_evpn_role: server
    default_overlay_routing_protocol: ibgp
    default_underlay_routing_protocol: isis-sr
    default_overlay_address_families:
      - vpn-ipv4
    default_evpn_encapsulation: mpls

...