---
dc_name: DC2

evpn_overlay_bgp_rtc: true

spine:
  defaults:
    platform: cEOS
    loopback_ipv4_pool: 192.168.255.0/24
    # ASN to be used by BGP
    bgp_as: 65220
  nodes:
    # Name of the node to be defined (must be consistent with definition in inventory)
    - name: spine1-DC2
      # Device ID definition. An integer number used for internal calculations (ie. IPv4 address of the loopback_ipv4_pool among others)
      id: 14
      # Management IP to be assigned to the management interface
      mgmt_ip: 192.168.0.14/24
      downlink_pools:
        - ipv4_pool: 10.20.0.0/27
          downlink_interfaces:
            - Ethernet2
            - Ethernet3
            - Ethernet4
            - Ethernet5
        - ipv4_pool: 10.114.21.0/30
          downlink_interfaces: 
            - Ethernet6
    - name: spine2-DC2
      id: 15
      mgmt_ip: 192.168.0.15/24
      downlink_pools:
        - ipv4_pool: 10.20.0.32/27
          downlink_interfaces:
            - Ethernet2
            - Ethernet3
            - Ethernet4
            - Ethernet5
        - ipv4_pool: 10.115.21.0/30
          downlink_interfaces: 
            - Ethernet6
    - name: spine3-DC2
      id: 16
      mgmt_ip: 192.168.0.16/24
      downlink_pools:
        - ipv4_pool: 10.20.0.64/27
          downlink_interfaces:
            - Ethernet2
            - Ethernet3
            - Ethernet4
            - Ethernet5
        - ipv4_pool: 10.116.21.0/30
          downlink_interfaces: 
            - Ethernet6
l3leaf:
  defaults:
    platform: cEOS
    loopback_ipv4_pool: 192.168.255.0/24
    vtep_loopback_ipv4_pool: 10.255.1.0/24
    uplink_interfaces: ['Ethernet3', 'Ethernet4', 'Ethernet5']
    uplink_switches: ['spine1-DC2', 'spine2-DC2', 'spine3-DC2']
    #uplink_ipv4_pool: 10.10.0.0/24
    mlag_interfaces: ['Ethernet1', 'Ethernet2']
    mlag_peer_ipv4_pool: 10.255.2.0/24
    mlag_peer_l3_ipv4_pool: 10.255.3.0/24
    virtual_router_mac_address: 00:1c:73:00:00:99
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
  node_groups:
    - group: DC2_L3_LEAF12
      bgp_as: 65212
      nodes:
        # Definition of hostnames under the node_group
        - name: leaf1-DC2
          id: 31
          mgmt_ip: 192.168.0.31/24
          # Definition of the port to be used in the uplink device facing this device.
          # Note that the number of elements in this list must match the length of 'uplink_switches' as well as 'uplink_interfaces'
          uplink_switch_interfaces:
            - Ethernet2
            - Ethernet2
            - Ethernet2
        - name: leaf2-DC2
          id: 32
          mgmt_ip: 192.168.0.32/24
          # Definition of the port to be used in the uplink device facing this device.
          # Note that the number of elements in this list must match the length of 'uplink_switches' as well as 'uplink_interfaces'
          uplink_switch_interfaces:
            - Ethernet3
            - Ethernet3
            - Ethernet3
    - group: DC2_L3_LEAF34
      bgp_as: 65234
      nodes:
        # Definition of hostnames under the node_group
        - name: leaf3-DC2
          id: 33
          mgmt_ip: 192.168.0.33/24
          # Definition of the port to be used in the uplink device facing this device.
          # Note that the number of elements in this list must match the length of 'uplink_switches' as well as 'uplink_interfaces'
          uplink_switch_interfaces:
            - Ethernet4
            - Ethernet4
            - Ethernet4
        - name: leaf4-DC2
          id: 34
          mgmt_ip: 192.168.0.34/24
          # Definition of the port to be used in the uplink device facing this device.
          # Note that the number of elements in this list must match the length of 'uplink_switches' as well as 'uplink_interfaces'
          uplink_switch_interfaces:
            - Ethernet5
            - Ethernet5
            - Ethernet5
gwleaf:
  defaults:
    platform: cEOS
    loopback_ipv4_pool: 192.168.255.0/24
    vtep_loopback_ipv4_pool: 10.255.1.0/24
    uplink_interfaces: ['Ethernet3', 'Ethernet4', 'Ethernet5']
    uplink_switches: ['spine1-DC2', 'spine2-DC2', 'spine3-DC2']
    mlag_interfaces: ['Ethernet1', 'Ethernet2']
    mlag_peer_ipv4_pool: 10.255.2.0/24
    virtual_router_mac_address: 00:1c:73:00:00:99
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
    bgp_as: 1
  nodes:
    # Name of the node to be defined (must be consistent with definition in inventory)
    - name: BL1-DC2
    # Device ID definition. An integer number used for internal calculations (ie. IPv4 address of the loopback_ipv4_pool among others)
      id: 95
      # Management IP to be assigned to the management interface
      mgmt_ip: 192.168.0.95/24
      uplink_interfaces: ['Ethernet6', 'Ethernet7', 'Ethernet8']
      uplink_switch_interfaces:
          - Ethernet6
          - Ethernet6
          - Ethernet6
