---
tenants:
  # Tenant A VRFs / VLANs
  - name: Tenant_A
    enable_mlag_ibgp_peering_vrfs: false
    mac_vrf_vni_base: 10019
    vrfs:
      - name: VRF_A
        vrf_vni: 19
        vtep_diagnostic:
          loopback: 10
          loopback_ip_range: 10.255.10.0/24
        svis:
          - id: 110
            name: VRF_A_VLAN_110
            tags:
              - dc1_pod1
            enabled: true
            ip_address_virtual: 10.1.10.1/24
          - id: 112
            name: VRF_A_VLAN_112
            tags:
              - dc1_pod2
            enabled: true
            ip_address_virtual: 10.1.12.1/24
          - id: 120
            name: VRF_A_VLAN_120
            tags:
              - dc2_pod1
            enabled: true
            ip_address_virtual: 10.1.20.1/24
          - id: 122
            name: VRF_A_VLAN_122
            tags:
              - dc2_pod2
            enabled: true
            ip_address_virtual: 10.1.22.1/24
      
      - name: VRF_B
        vrf_vni: 20
        vtep_diagnostic:
          loopback: 20
          loopback_ip_range: 10.255.20.0/24
        svis:
          - id: 111
            name: VRF_B_VLAN_111
            tags:
              - dc1_pod1
            enabled: true
            ip_address_virtual: 10.1.11.1/24
          - id: 113
            name: VRF_B_VLAN_113
            tags:
              - dc1_pod2
            enabled: true
            ip_address_virtual: 10.1.13.1/24
          - id: 121
            name: VRF_B_VLAN_121
            tags:
              - dc2_pod1
            enabled: true
            ip_address_virtual: 10.1.21.1/24
          - id: 123
            name: VRF_B_VLAN_123
            tags:
              - dc2_pod2
            enabled: true
            ip_address_virtual: 10.1.23.1/24
